### ISSUE TITLE
Add "secondary" / "danger"-style buttons

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/re-cy-cle#21]
For TMS we need buttons that have a "danger" look (for actions deleting stuff), and a "secondary" look, for actions like "Close".

I think `<Button tone="secondary" />` might make sense.

**Comment by SpaceK33z** [comment]
Tip: when in doubt about the prop name, I always check out some other style guides: https://github.com/CodeYellowBV/re-cy-cle/#inspiration

**Comment by Rutger** [comment]
@RogerKemp How do button colors behave in our design language? 
We usually use the primary branding color for normal buttons. That means we have red normal buttons in HN.
We should vary the colors by the app theme. Probably use black buttons for a `tone="danger"`-style in HN, and use red in TMS?

**Comment by SpaceK33z** [comment]
Not Roger, but I think we should make these tones configurable in the theme settings.
