### ISSUE TITLE
RadioButtons: toggle focus state

### ISSUE THREAD

**Issue by RogerKemp** [CodeYellowBV/re-cy-cle#29]
When tabbing through a form it's not obvious a user is focussed on a radio toggle, since it doesn't have a focus state style.

I suggest using the same style as the text input fields.

**Comment by SpaceK33z** [comment]
This works already, notice the colored border around the buttons when focused:

<img width="522" alt="screen shot 2017-09-19 at 18 07 12" src="https://user-images.githubusercontent.com/533616/30602611-6b8ebad2-9d65-11e7-9968-56f2aba45f94.png">

**Comment by SpaceK33z** [comment]
It only worked when you tab through a form, not when you click on it. I fixed that now.
