### ISSUE TITLE
Button: add focus state

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/re-cy-cle#52]
When a button is focused, there is no visual feedback at all. This is kinda crappy.

**Comment by Taym95** [comment]
What do you mean exactly by visual feedback?

**Comment by SpaceK33z** [comment]
For example here: https://css-in-js-experiences.ga/bootstrap/#

If you press <kbd>tab</kbd> a few times, you'll notice that e.g. the "Learn more" button has a box-shadow applied: 
<img width="190" alt="screen shot 2017-10-04 at 21 22 15" src="https://user-images.githubusercontent.com/533616/31195297-1d303c4e-a94a-11e7-8d6b-e62fc571e00e.png">

In re-cy-cle we don't have something like that, so if you like tabbing your way through a form, you won't see when a button is focused.
