### ISSUE TITLE
Tab behavior of FancySelect is broken

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/re-cy-cle#57]
When I'm typing in a FancySelect and press tab, something invisible is focused. Only upon pressing tab one more time the next input is focused.

**Comment by SpaceK33z** [comment]
The dropdown button at the right is selected when you press tab. This bug is a consequence of the issue in #52, because of this bug you can't see that the button is selected. However perhaps it's best to use `tabIndex` to skip this dropdown button completely when tabbing.
