### ISSUE TITLE
TypeAhead input is not resetable

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/re-cy-cle#58]
The TypeAhead supports a `value` prop, but when setting that value to `''` or to `null`, the typeAhead isn't reset.

Setting an empty value does clear the input in this example: http://downshift.netlify.com/?selectedKind=Examples&selectedStory=controlled&full=0&down=1&left=1&panelRight=0

**Comment by SpaceK33z** [comment]
I added a new story to the `TypeAhead` component: "controlled". In there I added a "Reset" button which sets the value to `''`. This works correctly, so can you provide a code sample to reproduce?

**Comment by stam** [comment]
Hmm weird, it seems to work now, must have done something weird myself
