### ISSUE TITLE
Issues with inconsistent alignment

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/re-cy-cle#61]
The `<Row>` component has a left and right margin, which makes it difficult to properly align text when something above it doesn't have a `<Row>`. Example:

```jsx
<Heading>Title</Heading>
<Row>
  <Col>
    Foo
  </Col>
  <Col>
     Bar
  </Col>
</Row>
```

In this case, "Foo" is intended ~20px. I would expect there to be a margin between the Foo and Bar columns, but not at the left and the right.

Furthermore, the `<Button>` component has a margin around it which also makes it difficult to properly align. I _think_ it should only have a margin-right.

cc @JasperStam

**Comment by SpaceK33z** [comment]
<img width="551" alt="screen shot 2017-10-24 at 14 35 48" src="https://user-images.githubusercontent.com/533616/31943315-a6c73790-b8c8-11e7-898f-3e555358f062.png">

@JasperStam see the screenshot. Note that I only fixed the margin for the `<Button/>` component. Did you have other issues?

**Comment by stam** [comment]
Removing the Button margin fixes that issue.
I still however struggle with the margin/padding on Rows and Column.

The Col has padding-left & -right of `0.5rem`, and the Row has margin-left & -right of `-0.5rem`. In my use case I sometimes use Row without a Col, or a Col without a Row, causing it to be misaligned.

**Comment by SpaceK33z** [comment]
Hmm yes but in that case you really need to wrap a Col around it. Even if we would fix the left and right margin and replace it with some other trick, using it without a Col would produce weird effects (since it doesn't have the same properties as a Col). 

I misunderstood you at first, I thought it was purely about the margin of components outside of Row completely.

Gonna close this since I'm not going to fix that
