### ISSUE TITLE
SingleDateTimePicker internal state doesn't update correctly on external update

### ISSUE THREAD

**Issue by stefanmajoor** [CodeYellowBV/re-cy-cle#74]
So basically, my code is like. This, I create an observable like this:
```
    @observable startDate = moment();
```

And an element like this
```
<SingleDatePicker
    value={this.startDate}
    onChange={this.changeStartDate}
/>
```

Lateron in the code, I change the startDate like this:
```
    // Sync manual changes of the date to the shown svg.
    changeStartDate = (name, value) => {
        this.startDate = value;
       (..)
    };
```

Now the input field, changes, but the date-selecting pop up doesn't change accordingly:

![image](https://user-images.githubusercontent.com/7164637/33549041-8d1a3b4e-d8e9-11e7-81b4-dada8de17ca8.png)

If however you change the date from the input, the pop-up state is synced:
![image](https://user-images.githubusercontent.com/7164637/33549165-e595e8c2-d8e9-11e7-8e74-5a0ce20c3669.png)

**Comment by SpaceK33z** [comment]
I can't reproduce this at all, but there is another issue that could be related; if you enter the date via the input it behaves very weirdly. E.g. putting the cursor after the year, and pressing backspace once doesn't remove the character.

I added a `controlled` story to the `SingleDatePicker` component to test this more easily.

**Comment by stefanmajoor** [comment]
I have replicated this at: https://codesandbox.io/s/310m574rxm
