### ISSUE TITLE
SingleDatePicker: modifying input is completely broken

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/re-cy-cle#75]
In https://github.com/CodeYellowBV/re-cy-cle/issues/74#issuecomment-348931093 we discovered that when you try to modify the input instead of using the datepicker, selecting a day is really hard.

For example setting your cursor right after the year, and then pressing backspace doesn't remove the last character like you'd expect.

I think we need to have an internal state in the SingleDatePicker that keeps track of the exact input value, and only triggers `onChange()` when the date is complete (the full dd-mm-yyyy value is entered).

**Comment by SpaceK33z** [comment]
Downgraded react-day-picker temporarily, https://github.com/gpbl/react-day-picker/issues/584

**Comment by reinartg** [comment]
@SpaceK33z I tried downgrading existing DayPickerInput from v7 to v6.2.1, but getting several errors, Do you have a code snippet of the DayPickerInput running on v6.2.1 using state and formatDate?

**Comment by SpaceK33z** [comment]
@reinartg You can't use the `formatDate` and `parseDate` props with `DayPickerInput` as far as I know, those were new in v7. So I removed that part of the code. I don't know what you mean with `state` exactly.

**Comment by reinartg** [comment]
I am sending in a selectedDay state into the value prop. I need this state to be formatted into this format DD.MM.YYYY and to be shown correctly in IE

**Comment by SpaceK33z** [comment]
I have no idea how that would work. Btw is this a question related to this repository, re-cy-cle, or purely something from react-day-picker?

**Comment by reinartg** [comment]
Just a question on how to format the input value in v6.2.1 since formatDate and parseDate does not exist in that version, but I managed to figure it out.
